-- Phase 4B-2D-A — start-time QC checklist snapshot/freeze.
--
-- Purely additive: a new nullable JSON column holding the effective
-- checklist definition (id/label/category/order/mandatory per item) frozen
-- onto a QCInspection at Start, so submitChecklist/decide can validate and
-- evaluate mandatory-completeness against it instead of re-resolving
-- QCChecklistTemplate live (see the Phase 4B-2D discovery report's two
-- HIGH-severity findings this closes).
--
-- The existing `checklist` column's contract (array of submitted results
-- only, replaced wholesale on every submit) is deliberately left unchanged —
-- this is a second, independent field, not a reshaping of `checklist`,
-- specifically so the pre-existing Phase 4B-1 test suite's assertion on
-- `checklist`'s array length did not have to change.
--
-- Verified immediately before this migration: 0 QCInspection rows exist in
-- this environment, so there is no backfill or backward-compatibility
-- concern for any historical row.
ALTER TABLE "QCInspection" ADD COLUMN "checklistDefinition" JSONB;
